import './globals.css';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <img src="/images/mainBG.png" className="main-bg" />
                <div className="layout">{children}</div>
            </body>
        </html>
    );
}
