import './globals.css';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <header className="header">
                    <img src="/images/logo1.svg" className="logo" />
                </header>

                <div className="layout">{children}</div>
            </body>
        </html>
    );
}
